import { describe, expect, it, vi } from "vitest";

vi.mock("./fonts", () => ({
	geistSans: { variable: "--font-geist-sans" },
	geistMono: { variable: "--font-geist-mono" },
}));

import { metadata } from "./layout";

describe("RootLayout metadata", () => {
	it("defines the default page metadata", () => {
		expect(metadata).toMatchObject({
			title: "Create Next App",
			description: "Generated by create next app",
		});
	});
});
