import { describe, expect, it } from "vitest";

import { metadata } from "./layout";

describe("RootLayout metadata", () => {
	it("defines the default page metadata", () => {
		expect(metadata).toMatchObject({
			title: "Create Next App",
			description: "Generated by create next app",
		});
	});
});
